name: Code Quality
on: [push, pull_request]
jobs:
  formatting:
    name: validate formatting
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get dependencies
        run: go mod download
      - name: Formatting
        run: diff <(gofmt -d ./...) <(echo -n)
  generate:
    name: validate code generated
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get dependencies
        run: go mod download
      - name: go generate
        run: go generate
      - name: validate generated code
        run: sh .github/go-generate-test.sh