name: Go
on:
  push:
    branches:
      - !docs/*
  pull_request:
    branches:
      - !docs/*
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: code formatting
      run: go fmt ./... 2>&1 | read

    - name: Run tests
      run: go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload test coverage
      run: |
        for pkg in $(go list ./...); do
            go test -coverprofile=$(echo $pkg | tr / -).cover $pkg
        done
        echo "mode: set" > c.out
        grep -h -v "^mode:" ./*.cover >> c.out
        rm -f *.cover
        ./cc-test-reporter after-build --debug --exit-code $? --prefix github.com/andersfylling/disgord/
      
